services:
  - type: web
    name: dumbo-backend
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      bash build.sh
    startCommand: python -m gunicorn backend.dumbo.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dumbo-db
          property: connectionString
      - key: CACHE_URL
        fromService:
          name: dumbo-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: dumbo-redis
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://dumbo-frontend.onrender.com

  - type: worker
    name: dumbo-worker
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      bash build.sh
    startCommand: celery -A backend.dumbo worker --loglevel=INFO
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dumbo-db
          property: connectionString
      - key: CACHE_URL
        fromService:
          name: dumbo-redis
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          name: dumbo-redis
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: https://dumbo-frontend.onrender.com

  - type: redis
    name: dumbo-redis
    plan: free
    region: frankfurt

  - type: static
    name: dumbo-frontend
    env: static
    buildCommand: |
      npm install --prefix frontend
      npm run --prefix frontend build
    staticPublishPath: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://dumbo-2.onrender.com


databases:
  - name: dumbo-db
    plan: free
    region: Frankfurt